export const EXPENSE_STATUS = {
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING'
};

export const EXPENSE_TYPE = {
  EXPENSE: 'EXPENSE',
  INVOICE: 'INVOICE'
};
