version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: expense-postgres
    environment:
      POSTGRES_DB: expense_segmentation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - expense-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expense_segmentation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - expense-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  expense-network:
    driver: bridge
